### ISSUE TITLE
Plugin Missing

### ISSUE THREAD

**Issue by carvelli** [kalilistic/xivplugins#14]
Hi!

As far as I can tell from the site, two of my plugins (Fish Notify, Slice is Right) are in the database - while the latest one I've created (Palace Pal) is not. Could you maybe check if there's an issue related to that somehow? All of them are listed in https://raw.githubusercontent.com/carvelli/Dalamud-Plugins/master/dist/pluginmaster.json 

At least a rough github search for `IDalamudPlugin` also finds it for me - https://github.com/search?l=C%23&o=desc&q=IDalamudPlugin&s=indexed&type=Code - but then I don't know how you actually query for new plugins.

**Comment by kalilistic** [comment]
This has happened once or twice before for new plugins. The last time I flipped through all search pages and the missing plugin wasn't in the gh results. I assume some indexing issue on the gh side. I do see the plugin on your search - but wonder if the result sets are the same for users (or different since it's your repo).

I'll add this one manually. I have some ideas for future improvements to hopefully avoid the issue.

**Comment by kalilistic** [comment]
Fixed - it's showing up now.
